### ISSUE TITLE
Customize period check for some locales

### ISSUE THREAD

**Issue by naokomc** [vlad-timotei/wpgp-tools#1]
For the same reason I [provided on WP Meta Trac](https://meta.trac.wordpress.org/ticket/5671#comment:5), the "missing period" error should be customized for some locales.

> These are different variations of the period symbol that I know of.
> 
> * Japanese and Chinese: [。](https://en.wiktionary.org/wiki/%E3%80%82)
> * Hindi, Bengali, and Assamese: [।](https://en.wiktionary.org/wiki/%E0%A5%A4)
> * Armenian: [։](https://en.wiktionary.org/wiki/%D6%89)
> * Khmer: [។](https://en.wiktionary.org/wiki/%E1%9F%94)
> * Myanmar/Burmese: [။](https://en.wiktionary.org/wiki/%E1%81%8B)
> * Tibetan: [།](https://en.wiktionary.org/wiki/%E0%BC%8D)
> * Urdu: [۔](https://en.wiktionary.org/wiki/%DB%94)
> * Thai: no period

Bonus point if these can also be automatically sorted, but I'm happy simply if the check between "." and "。" is implemented 😝

> But in Japanese, we use the English period when the string is not translated (e.g. "[All Rights Reserved."](https://translate.wordpress.org/consistency/?search=All+Rights+Reserved.&set=ja%2Fdefault&project=]). I can't confirm but I think this is the same for others. Happy to do more research once we decide on the direction!
> 
> Also, the ellipsis (`...`) at the end of a sentence tends to stay as-is for many locales (Japanese uses a native character for it, which is a single letter: `…`). There may be other exceptions like this.

**Comment by vlad-timotei** [comment]
Thank you for addressing this! The check for the ending character is complex because it has to also chek if:
1. original ends with `).` and translation is inversed `.)` => there should no warning (locale punctuation rules)
2. same with `".` versus `."`  
3. same with  `</tag>.` versus `.</tag>`
4. and the matter you addressed, if there is another coresponding period symbol instead

...besides elipsis (currently ignored! - has to be fixed as well) and column.

Version 1.2 (current one) succesfully warns for additional period in cases 1, 2, 3 and missing period in cases 1 and 2 only (fails in 3). Nothing for 4. Yet!

Because all of these checks have to be performed, my approach for the various period symbols alternative would be to add a user setting to tell the script to check against something else instead of period. This would be under the Locale Specific Checks where currently there is only Romanian checks.

![image](https://user-images.githubusercontent.com/65488419/118250356-0d478700-b4af-11eb-81d1-b8a65c861177.png)
- either a user defined input setting
> My locale uses `<input type="text" value="Enter your locale period alternative symbol here">` as a period alternative symbol, so the checks will be made against this symbol instead of period.

- or a locale section with a by defaut enabled setting for their alternative symbol (pre-defined), among other things the locale wants to check (ro_Ro has a bunch of custom checks): 

> Check for  `x` instead of `.` (where x is the  locale's alternative for period)

First option above would allow any locale to implement the correct check without me having to implement it as a pre-defined locale rule and  if a locale needs more specific defined checks, those can be added as well in the future. What's your opinion on this?

I'll try to come up with a visual checks schema to easily see what does it miss and how can it be fixed.

**Comment by vlad-timotei** [comment]
Here's my proposed solution. The new code is tested but needs furher testing and more eyes to verify if the checks logic is valid.

#### A. Custom period symbol setting in the settings window
![image](https://user-images.githubusercontent.com/65488419/118801767-0b643600-b8aa-11eb-8b02-a88e07e2cc47.png)

#### B. New checks logic for the ending character

If original end character is **different** than translation end character, then the following checks will happen, in this **order** and next checks in this list will be **skipped** if one of them is true:

1. If translation ends with space &rarr; Warning: Additional end space

2. If original ends with space &rarr; Warning: Missing end space

3. If all of these &rarr; Warning: Missing end period symbol

- [x] original ends with `.` 
- [x] translation does NOT end with period symbol ( `.` or user defined)
- [x] translation does NOT end with `…` that might be in original as `...`
- [x] original `</tag>.` is NOT translated as `.</tag>` (tag - period symbol swap) 
- [x] original `".` is NOT translated as `."` (character - period symbol swap)
 (where " can be any non-alpha-non-numeric symbol such as `) ' " ” ] }`)

4. If all of these &rarr; Warning: Additional end period symbol

- [x] original does NOT end with `.`
- [x] translation ends with period symbol ( `.` or user defined)
- [x] original does NOT end with `…` that might be translated as `...`
- [x] original `.</tag>` is NOT translated as `</tag>.` (period symbol - tag swap) 
- [x] original `."` is NOT translated as `".` (period symbol - character swap)
 (where " can be any non-alpha-non-numeric symbol such as `) ' " ” ] }`)
			
	

5. If original ends with `:` &rarr; Warning: Missing end colon

6. If translation ends with `:` &rarr;Warning:  Additional end colon 

@naokomc what do you think about this logic? Does it miss any scenario? TIA

**Comment by vlad-timotei** [comment]
Scanning trough wp/dev/ja/default/ the numbers of warnings are considerably lower - 49 in all 4294 strings - and as far as I can tell they are more positive than false positive. Sure, a human needs to asses if the warning is correct, but the guidance is there (most of those 49 are additional 。 where there is no . at the end or 。 instead of !

Closing this now. Feel free to open a new issue for any issues.

**Comment by vlad-timotei** [comment]
For anyone reading this later, in 1.4, while fixing https://github.com/vlad-timotei/wpgp-tools/issues/16, the checks order will change a bit. If there are any issues, let me know. New checks algorithm:

If original end character is **different** than translation end character, then the following checks will happen, in this **order** and next checks in this list will be **skipped** if one of them is true:

1. If translation ends with space &rarr; Warning: Additional end space

2. If original ends with space &rarr; Warning: Missing end space

3. If original ends with `:` &rarr; Warning: Missing end colon

4. If translation ends with `:` &rarr;Warning:  Additional end colon 

5. If original ends with `?` &rarr; Warning: Missing end question mark

6. If original ends with `!` &rarr; Warning: Missing end exclamation mark 

7. If original ends with `.` and **none** of these are true &rarr; Warning: Missing end period symbol
     - [x] translation ends with period symbol ( `.` or user defined)
     - [x] original `".` is  translated as `."` (a character - period symbol swap)
      *`"` can be any non-alpha-non-numeric symbol such as `) ' " ” ] }`*
     - [x] original `</tag>.` is  translated as `.</tag>`  (a tag - period symbol swap) 
     - [x] original end `...` is translated as `…` 
 
8. If translation ends with a period symbol ( `.` or user defined) and  **none** of these are true <br> &rarr; Warning: Additional end period symbol
     - [x] original ends end with `.`
     - [x] original `."` is translated as `".` (period symbol - character swap)
      *`"` can be any non-alpha-non-numeric symbol such as `) ' " ” ] }`*
     - [x] original `.</tag>` is translated as `</tag>.` (period symbol - tag swap) 
     - [x] original end  `…`  is translated as  `...`
