### ISSUE TITLE
The "search in the whole project" feature only searches in current strings. 

### ISSUE THREAD

**Issue by NekoJonez** [vlad-timotei/wpgp-tools#11]
I was working on: https://translate.wordpress.org/projects/wp-plugins/broken-link-checker/stable/nl-be/default/?filters%5Btranslated%5D=yes&filters%5Bstatus%5D=waiting&page=12

And I wanted to check if I translated "broken link"' to "gebroken link"... But when I searched in the current project, I only got the current strings that I already tweaked and not in the waiting strings I imported and set to waiting.

**Comment by vlad-timotei** [comment]
Thank you for the issue. Consistency tools' main purpose is to search in **already translated (approved)** strings to see how other translators/yourself in the past have translated a certain word, so that is intentionally set this way to look up only in current strings. I wouldn't want to see waiting strings when I perform this search because *those could be wrong* (from a contributor). Your case is an exception where waiting strings are your own. Since it's an exception case, I'm going to close this as *won't fix*. For such a scenario I guess you could use the built in GlotPress search form in the top part 😃
