### ISSUE TITLE
In the options "broken placeholders" has no "enable/disable"

### ISSUE THREAD

**Issue by NekoJonez** [vlad-timotei/wpgp-tools#41]
In the options, the "broken placeholders" has no "enable/disable". I would either add that option or remove it from the settings menu, since it gives an incomplete impression.

**Comment by vlad-timotei** [comment]
This is caused by a simplification of code made in 

How it used to look:
![image](https://user-images.githubusercontent.com/65488419/136666371-e7bbe9af-0f4c-43c4-81b6-1e4d9d32fb07.png)

Fixed to:

![image](https://user-images.githubusercontent.com/65488419/136666782-077f6c07-41af-4968-a155-526af13a5e71.png)
