### ISSUE TITLE
Warn & prevent doesn't work anymore.

### ISSUE THREAD

**Issue by NekoJonez** [vlad-timotei/wpgp-tools#44]
I have several settings on warn & prevent like spaces, double spaces and the tools WARNS after the fact but doesn't prevent saving.

**Comment by vlad-timotei** [comment]
I can't reproduce this. Can you give me an example where this happens? It happens consistently on a certain string?

For double spaces, WPGPT first checks the number of double spaces in original.  Then, we have 3 cases:

1. Original === Translation =>  it doesn't warn, as 99% of the time, those double spaces are by design intended to be there.

2. Original < Translation => it either shows a warning and block or a notification (if you set it as a notification or as a warning)

3. Original > Translation => it only shows a notification (doesn't matter what you set up) because 99% of the times translators will intentionally choose not to put a double space that they consider a mistake. It shows a notification later just in case you missed it.

Is this anyhow different than how things work on your end?

**Comment by NekoJonez** [comment]
Sadly enough, it doesn't... :( Makes debugging less easy. :(

I did notice something that's somewhat related to this ticket but since it's more of a feature, I'm going to make a new ticket for it.

But, I cleaned my cache and that seems to do the trick.
