### ISSUE TITLE
[Small enhancement] Don't throw a warning for perdiod as separator

### ISSUE THREAD

**Issue by Presskopp** [vlad-timotei/wpgp-tools#52]
**Is your feature request related to a problem? Please describe.**
The original string "number_format_thousands_sep" indicates the seperator and doesn't need a translation. In many cases, it will be "translated" as a simple period. But this gives a warning "Additional end perdiod (.)"

**Describe the solution you'd like**
Don't show warnings for "number_format_thousands_sep" and "number_format_decimal_point" or don't show warnings if the translated string is only 1 character

**String URL to exemplify**
https://translate.wordpress.org/projects/wp/dev/de/default/?filters%5Bterm%5D=number_format

**Comment by vlad-timotei** [comment]
Hi and thank you for the issue!
This is a valid issue, but I'm not sure if it's efficient to check for this edge case every time, since this is probably very rare, correct me if I'm wrong. 

I am aware that thse checks have and will always have false warnings, because they can't outsmart a human mind, so we have the Approve with warning checkbox for when this happens.

However, if you feel this is an annoying issue that happens often enough to deserve its own case handling, let me know.
For now, this is a _maybe-later_ for me. :)

**Comment by psmits1567** [comment]
Vladt it is not only the single dot but also a single comma. So the proposal to check for the length would be the best solution. It probably only happens in projects that handles amounts or quantities

**Comment by vlad-timotei** [comment]
@psmits1567 WPGPT doesn't check for additional ending comma. 😀 
See [this example](https://translate.wordpress.org/projects/wp/dev/nl/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=3084&filters%5Btranslation_id%5D=9703600) 
There is no warning for it. 

But sure, if this happens a lot, a check for 1 character length could be implemented.

**Comment by Presskopp** [comment]
I can live without this being handled, I just thought you may wish to avoid confusion here.

**Comment by psmits1567** [comment]
That is correct vladt, but it would also need to be checked as difference in translation. And as such would raise a unnecessary warning by this addon or GlotDict

**Comment by vlad-timotei** [comment]
Started in https://github.com/vlad-timotei/wpgp-tools/commit/e24c67424f5aef9eaef8b5c65d574ada72e8a576 and continued in https://github.com/vlad-timotei/wpgp-tools/commit/69b8753b4faa8b832b630044659894f5f5922898.

If translation is a `.` and original contains `number_format` don't throw an error.
This fixes those cases where `.` is used as a number separator. 

The check is still performant because it is guarded by other previous checks, and not run on each string.

Fix will be available in 2.0.1 release.
