### ISSUE TITLE
Bulk GTE replacement - Can't undo "Don't replace ..."

### ISSUE THREAD

**Issue by NekoJonez** [vlad-timotei/wpgp-tools#60]
When you are setting up the bulk replacement for GTE's in the consistency tool, once you click "Don't translate..." you can't "unclick" it apart from refreshing the page. 
I think it would be more user friendly if it's possible somehow. For example, by adding a sort of "undo" button?

**Comment by vlad-timotei** [comment]
Thank you for the issue!
I agree the UI can be improved, but at the same time, it's not a feature I personally want to emphazise, as it's quite powerful, so better to use it only in extreme cases. :D 
Will think about this.

**Comment by vlad-timotei** [comment]
I'm closing this with a `maybe-later` / `wont-fix` tag because:
-  the implementation of a solution for this is not that straight forward (could break the actual functionality without extensive testing of the changes)
- the GTE should be super extra careful here, so mistakes should be minimal
- a refresh fixed an eventual mistake
