### ISSUE TITLE
Have an option to disable the logs from bulk replace for GTE's

### ISSUE THREAD

**Issue by NekoJonez** [vlad-timotei/wpgp-tools#68]
I'm cleaning up in nl_BE/nl_NL and it's quite annoying that for every 25 changes the tool gives an option to download a log... It would save me a bit of time if I could set an option (with the needed warning labels ofc) that doesn't generate the log.

**Comment by vlad-timotei** [comment]
Hi! 
Thank you for the issue.
However, I think the bulk replacement tool is a pretty powerful tool and it's easy to mess up with it.
That's why I think it is always mandatory to have a log of the replaced strings just in case you want to later manually revert some translations.

You can setup your browser to automatically download files, without asking for where to save them and that will save some time. But I don't think it's a good idea to skip this. 😄
