### ISSUE TITLE
Have on the history label also an indication of strings have that more than one translation in consistency viewer

### ISSUE THREAD

**Issue by NekoJonez** [vlad-timotei/wpgp-tools#69]
As the title says. Maybe this might be an overkill feature, but it would help PTE's/GTE's to easily find strings with a lot of different translations to create some consistency.

**Comment by vlad-timotei** [comment]
Ok, so this won't go into WPGPT, but I'll give you something to work you with. Let me explain why.
The consistency suggestions only load when you open the editor and that is because that is an expensive request that takes a while (at least 1s/string) so you don't know if a string has consistency suggestions (multiple/single) until you open the editor.

However, here's a snippet that you can manually run to load all consistency suggestions on that page and when that's done to also display a message in preview for each string with multiple consistency suggestions. 

1. Create a bookmark in your browser
2. Paste the code below in the URL field
3. Click it **on a loaded page with strings**

 It will trigger the load of all consistency suggestions and after about 1 minute (depending on how many strings you load per page) you will also get visual notifications on those rows that have multiple consistency suggestions. WPGPT must be active to work.

Code to insert into URL bookmark field:

```
javascript:const s=document.createElement("span");s.className="no-suggestions";const r=document.querySelectorAll(".suggestions__other-languages");r.forEach(e => e.append(s.cloneNode())),setTimeout(() => document.querySelectorAll(".wpgpt-consistency .gte-warning").forEach(w => {let p=w.closest(".editor"),t=document.querySelector(`#preview-${p.getAttribute("row")} td.translation`);t.appendChild(w.cloneNode(!0))}), 1e3 * r.length);
```

Here's the beautified snippet in case anyone wonders.

```javascript
const triggerSpan = document.createElement( 'span' );
triggerSpan.className = 'no-suggestions';
const allRows = document.querySelectorAll( '.suggestions__other-languages' );
allRows.forEach( rowSuggestion => {
	rowSuggestion.append( triggerSpan.cloneNode() );
} );
setTimeout( () => {
	document.querySelectorAll( '.wpgpt-consistency .gte-warning' ).forEach( warning => {
		const editor = warning.closest( '.editor' );
		const preview = document.querySelector( `#preview-${editor.getAttribute( 'row' )} td.translation` );
		preview.appendChild( warning.cloneNode( ! 0 ) );
	} );
}, allRows.length * 1000 );

```
Example:
![Screenshot 2022-10-20 at 21 50 33](https://user-images.githubusercontent.com/65488419/197033078-7e30d1e6-d6b4-4ec8-80e9-919dc57d38f8.png)
