### ISSUE TITLE
The "warnings" feature should be able to scan for url mistakes. 

### ISSUE THREAD

**Issue by NekoJonez** [vlad-timotei/wpgp-tools#8]
The "warnings" feature can give us an easy way to quickly find mistakes and improve them... But what if this feature could also pick up mistakes in url translations? 

I noticed that the fuzzy bot doesn't always fuzzy http:// to https:// changes (which is security wise an important change) and it would be neat if that could also appear in warnings... 

(The http:// to https:// is just an example!)

**Comment by vlad-timotei** [comment]
TBH, I thought this was already happening by default 😁 Seems it doesn't. 
Because I think this will be implemented at some point upstream and because I wouldn't want to add another option to enable/disable this, I am tempted to close this as a `wontfix`.

However, I understand the benefits of such a check, and I am thinking of an implementation that can perform such a check and also other user defined checks. 

In https://github.com/vlad-timotei/wpgp-tools/issues/16 a count of a certain symbol is required both in original and in translated string and then if those two don't match a warning should be generated. I am thinking about letting the user set what symbols they want to count and check. Even if it's not a symbol, one could easily add in that list the word `https://` and if the original has 1 `https://` and the translation has 0 `https://` a warning will be generated. 

Even with how things currently work, you could add `http://` as a warning word in the settings and you would still get a warning. 

As for other URL mistakes, GP already warns you if you enter a different URL. 

Let me know what you think about this. We could fix 2 issues and let users check for whatever they want with a single UI setting and implementation.

**Comment by vlad-timotei** [comment]
The above implementation will be included in 1.4. 
Feel free to add your input and let me know how this works for you!
